version: "3.9"
services:
  web:
    build: .
    ports:
      - "8080:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://user:123@db/db
  db:
    image: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_PASSWORD: 123
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - "dbdata:/var/lib/postgresql/data"
volumes:
  dbdata: